---
- hosts: packer
  remote_user: root
  gather_facts: false
  vars :
    maven_versions: [3.0.5, 3.2.3, 3.2.5, 3.3.9, 3.5.0, 3.5.2]
    jdk_download_urls: [
      "https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/slaves-resources/lastSuccessfulBuild/artifact/jdk-6u45-linux-x64.tar.gz",
      "https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/slaves-resources/lastSuccessfulBuild/artifact/jdk-7u80-linux-x64.tar.gz",
      "https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/slaves-resources/lastSuccessfulBuild/artifact/jdk-8u152-linux-x64.tar.gz",
      "https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/slaves-resources/lastSuccessfulBuild/artifact/jdk-9.0.1-linux-x64.tar.gz"
    ]
    jdk_short_versions: [6u45, 7u80, 8u152, 9.0.1]
    jdk_long_versions: [jdk1.6.0_45, jdk1.7.0_80, jdk1.8.0_152, jdk-9.0.1]
    jdk_symlink_names: [jdk1.6, jdk1.7, jdk1.8, jdk9]
    firefox_short_versions: [38esr, 45esr, 52esr]
    firefox_long_versions: [38.8.0esr, 45.5.0esr, 52.0.2esr]

  tasks:
  - name: Copy Pulp repos config
    copy:
      src: data/config/pulp/pulp.repo
      dest: /etc/yum.repos.d/pulp.repo
      owner: root
      group: root
      mode: 0644

  - name: Install EPEL7 repository
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present

  - name: Import EPEL7 repository key
    shell: rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7

  - name: Update all packages
    yum:
      name: "*"
      state: latest

  - name: Add user jenkins
    user:
      name: jenkins
      # droolsjbpm.ci1
      password: $6$rounds=656000$skw/fVgypJZWP8m1$04UK6Ax4.2hhJfcCbgGegNGl0brQtufYJd4lGn4Lw2RnZ8GQL50crLAd/PIU/.JC047TLybYfcdLL/27hkwlx0
      state: present

  - name: Copy bashrc file
    copy:
      src: data/config/bashrc
      dest: /home/jenkins/.bashrc
      owner: jenkins
      group: jenkins

  - name: Create ~/.ssh directory
    file:
      path: /home/jenkins/.ssh
      state: directory
      owner: jenkins
      group: jenkins

#  - name: Copy SSH config file
#    copy: src=data/config/ssh/config dest=/home/jenkins/.ssh/config owner=jenkins group=jenkins mode=0644

  - name: Copy SSH authorized_keys file
    copy:
      src: data/config/ssh/authorized_keys
      dest: /home/jenkins/.ssh/authorized_keys
      owner: jenkins
      group: jenkins
      mode: 0644

  - name: Install packages
    yum:
      pkg: "{{item}}"
      state: latest
    with_items:
     - git
     - tig
     - wget
     - mc
     - vim
     - unzip
     - iputils
     - bind-utils
     - findutils
     - htop
     - hub
     - firefox
     - tigervnc
     - tigervnc-server
     - docker
     - screen
     - lsof
     - bash-completion
     - bzip2
     - rng-tools
     - ansible

  - name: Copy Docker config
    copy:
      src: data/config/docker/docker
      dest: /etc/sysconfig/docker
      owner: root
      group: root
      mode: 0644

  - name: Start and enabled Docker Service
    service:
      name: docker
      state: started
      enabled: true

  - name: Change group of /var/run/docker.sock to enable easier access to Docker daemon for user jenkins
    file:
      path: /var/run/docker.sock
      owner: root
      group: dockerroot

  - name: Add user jenkins into group dockerroot
    user:
      name: jenkins
      groups: dockerroot

  - name: Start and enable RNGD Service
    service:
      name: rngd
      state: started
      enabled: true

  - name: Create ~/.vnc directory
    file:
      path: /home/jenkins/.vnc
      state: directory
      owner: jenkins
      group: jenkins

  - name: Copy VNC passwd file
    copy:
      src: data/config/vnc/passwd
      dest: /home/jenkins/.vnc/passwd
      owner: jenkins
      group: jenkins
      mode: 0600

  - name: Create ~/.m2 directory
    file:
      path: /home/jenkins/.m2
      state: directory
      owner: jenkins
      group: jenkins

  - name: Copy Maven settings.xml files
    copy:
      src: data/config/maven/{{ item }}
      dest: /home/jenkins/.m2/{{ item }}
      owner: jenkins
      group: jenkins
      mode: 0644
    with_items:
      - settings.xml
      - settings-consume-staging-repos.xml

  - name: Create tools directory
    file:
      path: /opt/tools
      state: directory
      recurse: yes
      owner: root
      group: root

  - name: Create tmp downloads directory
    file:
      path: /tmp/downloads
      state: directory
      owner: root
      group: root

### JDK ###
  - name: Download JDK archives
    get_url:
      url: "{{ item }}"
      dest: /tmp/downloads/
      validate_certs: no
    with_items:
      - "{{ jdk_download_urls }}"

  - name: Extract JDK archives
    unarchive:
      src: /tmp/downloads/jdk-{{ item }}-linux-x64.tar.gz
      dest: /opt/tools
      copy: no
      # owner: root
      # group: root
    with_items:
     - "{{ jdk_short_versions }}"

  - name: Create JDK symlinks
    file:
      src: /opt/tools/{{ item.0 }}
      dest: /opt/tools/{{ item.1 }}
      state: link
      mode: 0644
    with_together:
    - "{{ jdk_long_versions }}"
    - "{{ jdk_symlink_names }}"

### Maven ###
  - name: Dowload Maven archives
    get_url:
      url: https://archive.apache.org/dist/maven/maven-3/{{ item }}/binaries//apache-maven-{{ item }}-bin.tar.gz
      dest: /tmp/downloads
      owner: root
      group: root
    with_items:
     - "{{ maven_versions }}"

  - name: Extract Maven archives
    unarchive: copy=no src=/tmp/downloads/apache-maven-{{ item }}-bin.tar.gz dest=/opt/tools owner=root group=root
    with_items:
     - "{{ maven_versions }}"

  - name: Copy Maven extensions
    copy:
      src: data/config/maven/ext-{{ item }}/
      dest: /opt/tools/apache-maven-{{ item }}/lib/ext
      owner: root
      group: root
    with_items:
     - "{{ maven_versions }}"

  - name: Ensure local Maven repo directory exists
    file:
      path: /home/jenkins/.m2/repository
      state: directory
      owner: jenkins
      group: jenkins

  - name: Download Maven repo cache
    get_url:
      url: https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/maven-repo-cache/lastSuccessfulBuild/artifact/maven-repo-cache.tar.gz
      dest: /tmp/downloads/maven-repo-cache.tar.gz
      validate_certs: no
      owner: jenkins
      group: jenkins
      follow: yes

  - name: Extract Maven repo cache
    unarchive:
      src: /tmp/downloads/maven-repo-cache.tar.gz
      dest: /home/jenkins/.m2/repository
      copy: no

### Groovy ###
  - name: Download Groovy 2.x archive
    get_url:
      url: https://dl.bintray.com/groovy/maven/apache-groovy-binary-2.4.7.zip
      dest: /tmp/downloads

  - name: Extract Groovy 2.x archive
    unarchive:
      src: /tmp/downloads/apache-groovy-binary-2.4.7.zip
      dest: /opt/tools
      copy: no

  - name: Create Groovy 2.x symlink
    file:
      src: /opt/tools/groovy-2.4.7
      dest: /opt/tools/groovy-2.x
      state: link
      mode: 0644

### Firefox ###
  - name: Download Firefox archives
    get_url:
      url: https://ftp.mozilla.org/pub/firefox/releases/{{ item }}/linux-x86_64/en-US/firefox-{{ item }}.tar.bz2
      dest: /tmp/downloads
    with_items:
     - "{{ firefox_long_versions }}"

  - name: Created Firefox dirs to extract the archives into
    file:
      path: /tmp/downloads/firefox-{{ item }}
      state: directory
    with_items:
      - "{{ firefox_long_versions }}"

  - name: Extract Firefox archives into tmp dir
    unarchive:
      src: /tmp/downloads/firefox-{{ item }}.tar.bz2
      dest: /tmp/downloads/firefox-{{ item }}
      copy: no
    with_items:
      - "{{ firefox_long_versions }}"

  - name: Copy the extracted Firefox archives into /opt/tools
    shell: mv /tmp/downloads/firefox-{{ item.0 }}/firefox /opt/tools/firefox-{{ item.1 }}
    with_together:
      - "{{ firefox_long_versions }}"
      - "{{ firefox_short_versions }}"

  - name: Create git-repos dir
    file:
      path: /home/jenkins/git-repos
      state: directory

  - name: Create local Git cache
    shell: cd /home/jenkins/git-repos && git clone --bare https://github.com/{{ item }}
    with_items:
     - kiegroup/lienzo-core
     - kiegroup/lienzo-tests
     - errai/errai
     - dashbuilder/dashbuilder
     - kiegroup/kie-soup
     - kiegroup/appformer
     - kiegroup/droolsjbpm-build-bootstrap
     - kiegroup/droolsjbpm-knowledge
     - kiegroup/drlx-parser
     - kiegroup/drools
     - kiegroup/optaplanner
     - kiegroup/optashift-employee-rostering
     - kiegroup/jbpm
     - kiegroup/droolsjbpm-integration
     - kiegroup/droolsjbpm-tools
     - kiegroup/kie-uberfire-extensions
     - kiegroup/guvnor
     - kiegroup/appformer
     - kiegroup/kie-wb-playground
     - kiegroup/kie-wb-common
     - kiegroup/jbpm-form-modeler
     - kiegroup/drools-wb
     - kiegroup/optaplanner-wb
     - kiegroup/jbpm-designer
     - kiegroup/jbpm-wb
     - kiegroup/dashboard-builder
     - kiegroup/jbpm-dashboard
     - kiegroup/kie-docs
     - kiegroup/kie-wb-distributions
     - kiegroup/droolsjbpm-build-distribution
     - jboss-integration/kie-eap-modules

  - name: Owner of Git cache is Jenkins
    file:
      path: /home/jenkins/git-repos
      state: directory
      owner: jenkins
      group: jenkins
      mode: 0755
      recurse: yes

  - name: Symlink jbpm-console-ng -> jbpm-wb
    file:
      path: /home/jenkins/git-repos/jbpm-console-ng.git
      src: /home/jenkins/git-repos/jbpm-wb.git
      state: link
      owner: jenkins
      group: jenkins
      mode: 0755

# Clean-up
  - name: Remove temprorary directory
    file:
      path: /tmp/downloads
      state: absent

# Hack: decrease the image size by writing zeros into unsused parts of the disk
  - name: Decrease VM image size
    shell: cd / && (dd if=/dev/zero of=fillmeup || true) && sync && rm -f fillmeup
