---
- hosts: packer
  remote_user: root
  gather_facts: false

  vars :
    maven_versions: [3.3.9,3.5.0,3.5.2,3.5.4,3.6.0,3.6.2,3.6.3,3.8.1]
    maven_versions_needing_extension: [3.3.9,3.5.0,3.5.2,3.5.4,3.6.0]
    jdk_long_versions: [java-1.8.0-openjdk, java-11-openjdk]
    jdk_symlink_names: [jdk1.8, jdk11]
    jdk_cacerts_subdirs: ["jre/lib/security/cacerts", "lib/security/cacerts", "lib/security/cacerts", "lib/security/cacerts"]
    firefox_short_versions: [45esr, 52esr, 60esr]
    firefox_long_versions: [45.9.0esr, 52.9.0esr, 60.2.0esr]
    pme_version: 4.3
    pig_version: 1.0.5
    graalvm_version: 20.3.1.2
    operator_sdk_version: [v0.18.2,v1.2.0]
    golang_version: 1.14
    mercurial_version: 5.3.1
    openshift_clients_version: 4.4.12
    jenkins_script_security_approved_signatures_present:
      - method java.util.regex.Matcher find
      - method org.yaml.snakeyaml.Yaml load java.lang.String
      - new java.util.Properties
      - new org.yaml.snakeyaml.Yaml
      - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods getAt java.lang.Object java.lang.String
      - new java.lang.StringBuilder java.lang.String
    node_version: 12.16.2
    node_setup_url: https://rpm.nodesource.com/setup_12.x
    buildchain_version: 2.3.5
    npmclilogin_version: ^0.1.1
    # rhel_version=7|8 variable is set by Packer when calling Ansible, you have to set it when running the playbook directly
    # e.g. by using --extra-vars rhel_version=7
    ant_version: 1.10.9

  roles:
    - common
    - kie
    - kogito
    - rhba
    - rhba-osbs
    - rhba-sourceclear-integration
    - gh-api

  tasks:
  ### Clean up ###
  - name: Remove temporary directory
    file:
      path: /tmp/downloads
      state: absent

  # Hack: decrease the image size by writing zeros into unsused parts of the disk
  - name: Decrease VM image size
    shell: cd / && (dd if=/dev/zero of=fillmeup || true) && sync && rm -f fillmeup
...
