---
- hosts: packer
  remote_user: root
  gather_facts: false

  vars :
    maven_versions: [3.3.9,3.5.0,3.5.2,3.5.4,3.6.0,3.6.2]
    jdk_download_urls: [
      "https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/userContent/jdk-8u202-linux-x64.tar.gz",
      "https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/userContent/jdk-9.0.4-linux-x64.tar.gz",
      "https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/userContent/jdk-10.0.2-linux-x64.tar.gz",
      "https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/userContent/jdk-11.0.2-linux-x64.tar.gz"
    ]
    jdk_short_versions: [8u202, 9.0.4, 10.0.2, 11.0.2]
    jdk_long_versions: [jdk1.8.0_202, jdk-9.0.4, jdk-10.0.2, jdk-11.0.2]
    jdk_symlink_names: [jdk1.8, jdk9, jdk10, jdk11]
    firefox_short_versions: [45esr, 52esr, 60esr]
    firefox_long_versions: [45.9.0esr, 52.9.0esr, 60.2.0esr]
    pme_version: 3.8.1
    pig_version: 1.0.5
    jenkins_script_security_approved_signatures_present:
      - method java.util.regex.Matcher find
      - method org.yaml.snakeyaml.Yaml load java.lang.String
      - new java.util.Properties
      - new org.yaml.snakeyaml.Yaml
      - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods getAt java.lang.Object java.lang.String

  roles:
    - common
    - kie
    - kogito
    - rhba
    - rhba-osbs
    - rhba-sourceclear-integration

  tasks:
  ### Clean up ###
  - name: Remove temprorary directory
    file:
      path: /tmp/downloads
      state: absent

  # Hack: decrease the image size by writing zeros into unsused parts of the disk
  - name: Decrease VM image size
    shell: cd / && (dd if=/dev/zero of=fillmeup || true) && sync && rm -f fillmeup
...
