---
### Install RPM packages ###

- name: Install packages
  yum:
    pkg: "{{item}}"
    state: latest
  with_items:
   - firefox
   - tigervnc
   - tigervnc-server
   - docker

### Bash ###

- name: Copy bashrc file
  copy:
    src: data/config/bashrc
    dest: /home/jenkins/.bashrc
    owner: jenkins
    group: jenkins

### Docker ###

- name: Copy Docker config
  copy:
    src: data/config/docker/docker
    dest: /etc/sysconfig/docker
    owner: root
    group: root
    mode: 0644

- name: Start and enabled Docker Service
  service:
    name: docker
    state: started
    enabled: true

- name: Change group of /var/run/docker.sock to enable easier access to Docker daemon for user jenkins
  file:
    path: /var/run/docker.sock
    owner: root
    group: dockerroot

- name: Add user jenkins into group dockerroot
  user:
    name: jenkins
    groups: dockerroot

### VNC ###

- name: Create ~/.vnc directory
  file:
    path: /home/jenkins/.vnc
    state: directory
    owner: jenkins
    group: jenkins

- name: Copy VNC passwd file
  copy:
    src: data/config/vnc/passwd
    dest: /home/jenkins/.vnc/passwd
    owner: jenkins
    group: jenkins
    mode: 0600

- name: Copy VNC xstartup file
  copy:
    src: data/config/vnc/xstartup
    dest: /home/jenkins/.vnc/xstartup
    owner: jenkins
    group: jenkins
    mode: 0700

### Maven repository ###

- name: Copy Maven extensions
  copy:
    src: data/config/maven/ext-{{ item }}/
    dest: /opt/tools/apache-maven-{{ item }}/lib/ext
    owner: root
    group: root
  with_items:
   - "{{ maven_versions }}"

- name: Create ~/.m2 directory
  file:
    path: /home/jenkins/.m2
    state: directory
    owner: jenkins
    group: jenkins

- name: Copy Maven settings.xml files
  copy:
    src: data/config/maven/{{ item }}
    dest: /home/jenkins/.m2/{{ item }}
    owner: jenkins
    group: jenkins
    mode: 0644
  with_items:
    - settings.xml
    - settings-consume-staging-repos.xml

- name: Ensure local Maven repo directory exists
  file:
    path: /home/jenkins/.m2/repository
    state: directory
    owner: jenkins
    group: jenkins

- name: Download Maven repo cache
  get_url:
    url: https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/maven-repo-cache-master/lastSuccessfulBuild/artifact/maven-repo-cache.tar.gz
    dest: /tmp/downloads/maven-repo-cache.tar.gz
    validate_certs: no
    owner: jenkins
    group: jenkins
    follow: yes

- name: Extract Maven repo cache
  unarchive:
    src: /tmp/downloads/maven-repo-cache.tar.gz
    dest: /home/jenkins/.m2/repository
    copy: no

### Groovy ###

- name: Download Groovy 2.x archive
  get_url:
    url: https://dl.bintray.com/groovy/maven/apache-groovy-binary-2.4.7.zip
    dest: /tmp/downloads

- name: Extract Groovy 2.x archive
  unarchive:
    src: /tmp/downloads/apache-groovy-binary-2.4.7.zip
    dest: /opt/tools
    copy: no

- name: Create Groovy 2.x symlink
  file:
    src: /opt/tools/groovy-2.4.7
    dest: /opt/tools/groovy-2.x
    state: link
    mode: 0644

### Firefox ###

- name: Download Firefox archives
  get_url:
    url: https://ftp.mozilla.org/pub/firefox/releases/{{ item }}/linux-x86_64/en-US/firefox-{{ item }}.tar.bz2
    dest: /tmp/downloads
  with_items:
   - "{{ firefox_long_versions }}"

- name: Created Firefox dirs to extract the archives into
  file:
    path: /tmp/downloads/firefox-{{ item }}
    state: directory
  with_items:
    - "{{ firefox_long_versions }}"

- name: Extract Firefox archives into tmp dir
  unarchive:
    src: /tmp/downloads/firefox-{{ item }}.tar.bz2
    dest: /tmp/downloads/firefox-{{ item }}
    copy: no
  with_items:
    - "{{ firefox_long_versions }}"

- name: Copy the extracted Firefox archives into /opt/tools
  shell: mv /tmp/downloads/firefox-{{ item.0 }}/firefox /opt/tools/firefox-{{ item.1 }}
  with_together:
    - "{{ firefox_long_versions }}"
    - "{{ firefox_short_versions }}"

### Git repositories ###

- name: Create git-repos dir
  file:
    path: /home/jenkins/git-repos
    state: directory

- name: Create local Git cache
  shell: cd /home/jenkins/git-repos && git clone --bare https://github.com/{{ item }}
  with_items:
   - kiegroup/lienzo-core
   - kiegroup/lienzo-tests
   - errai/errai
   - dashbuilder/dashbuilder
   - kiegroup/kie-soup
   - kiegroup/appformer
   - kiegroup/droolsjbpm-build-bootstrap
   - kiegroup/droolsjbpm-knowledge
   - kiegroup/drools
   - kiegroup/optaplanner
   - kiegroup/optaweb-employee-rostering
   - kiegroup/jbpm
   - kiegroup/jbpm-work-items
   - kiegroup/droolsjbpm-integration
   - kiegroup/droolsjbpm-tools
   - kiegroup/kie-uberfire-extensions
   - kiegroup/guvnor
   - kiegroup/kie-wb-playground
   - kiegroup/kie-wb-common
   - kiegroup/jbpm-form-modeler
   - kiegroup/drools-wb
   - kiegroup/optaplanner-wb
   - kiegroup/jbpm-designer
   - kiegroup/jbpm-wb
   - kiegroup/dashboard-builder
   - kiegroup/jbpm-dashboard
   - kiegroup/kie-docs
   - kiegroup/kie-wb-distributions
   - kiegroup/droolsjbpm-build-distribution
   - jboss-integration/kie-eap-modules

- name: Owner of Git cache is Jenkins
  file:
    path: /home/jenkins/git-repos
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755
    recurse: yes

- name: Symlink jbpm-console-ng -> jbpm-wb
  file:
    path: /home/jenkins/git-repos/jbpm-console-ng.git
    src: /home/jenkins/git-repos/jbpm-wb.git
    state: link
    owner: jenkins
    group: jenkins
    mode: 0755
...