---
### Install RPM packages ###

- name: Install RCMTOOLS repository
  yum:
    name: http://download.devel.redhat.com/rel-eng/RCMTOOLS/latest-redhat-rcminternal-release-server-rhel-7.noarch.rpm
    state: present

- name: Import RCMTOOLS repository key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-rcminternal


- name: Install packages
  yum:
    pkg: ['brewkoji']
    state: latest

### Download PME ###

- name: Create tools directory for pme
  file:
    path: /opt/tools/pme
    state: directory
    recurse: yes
    owner: root
    group: root

- name: Dowload PME extension
  get_url:
    url: https://repo.maven.apache.org/maven2/org/commonjava/maven/ext/pom-manipulation-cli/{{pme_version}}/pom-manipulation-cli-{{pme_version}}.jar
    dest: /opt/tools/pme
    owner: root
    group: root

### Download and install PiG/PFG ###

- name: Install PNC CLI
  command: "pip install pnc_cli"

- name: Create tools directory for PiG
  file:
    path: /opt/tools/pig/product-files-generator
    state: directory
    recurse: yes
    owner: root
    group: root

- name: Dowload PiG extension
  get_url:
    url: https://repository-basic.engineering.redhat.com/nexus/repository/jb-prod-tooling-releases/org/jboss/prod/prod-files-generator/{{pig_version}}/prod-files-generator-{{pig_version}}-shaded.jar
    dest: /opt/tools/pig/product-files-generator
    validate_certs: False
    owner: root
    group: root

- name: Create PiG JAR symlinks
  file:
    src: /opt/tools/pig/product-files-generator/prod-files-generator-{{pig_version}}-shaded.jar
    dest: /opt/tools/pig/product-files-generator.jar
    state: link
    mode: 0644

### Configure Maven ###

- name: Add PME extension to Maven
  file:
    src: /opt/tools/pme/pom-manipulation-cli-{{pme_version}}.jar
    dest: /opt/tools/apache-maven-{{ item }}/lib/ext/pom-manipulation-cli-{{pme_version}}.jar
    state: link
    mode: 0644
  with_items:
  - "{{ maven_versions }}"

- name: Create qa tools directory
  file:
    path: /qa/tools/opt
    state: directory
    recurse: yes
    owner: root
    group: root

- name: Create qa tools Maven symlinks
  file:
    src: /opt/tools/apache-maven-{{ item }}
    dest: /qa/tools/opt/maven-{{ item }}-prod
    state: link
    mode: 0644
  with_items:
  - "{{ maven_versions }}"

### Prepare Maven repositories ###

- name: Create 70 repository
  file:
    path: /m2/70
    state: directory
    recurse: yes
    owner: jenkins
    group: jenkins
...