---
### Install NodeJS package ###

- name: Install NodeJS repository
  shell: curl -sL {{node_setup_url}} | sudo -E bash -

- name: Install NodeJS package
  yum:
    pkg: nodejs-{{node_version}}
    state: present

- name: Install Required packages by kogito-tooling
  yum:
    pkg: ['gcc-c++']
    state: latest

- name: Print Node version
  shell: node -v
  register: node

- debug: msg="{{ node.stdout }}"

- name: Install Yarn
  shell: npm install -g yarn --registry=${NPM_REGISTRY_URL}

- name: Install build-chain-action
  shell: npm install -g @kie/build-chain-action@{{buildchain_version}} --registry=${NPM_REGISTRY_URL}

- name: Install npm-cli-login
  shell: npm install -g npm-cli-login@{{npmclilogin_version}} --registry=${NPM_REGISTRY_URL}

### Configure jenkins user to use podman ###
- name: Copy podman config file
  copy:
    src: data/config/podman/podman.conf
    dest: /etc/sysctl.d/podman.conf
    owner: root
    group: root
    mode: '0644'
- name: add jenkins user to uids
  shell: usermod --add-subuids 10000-75535 jenkins

- name: add jenkins user to gids
  shell: usermod --add-subgids 10000-75535 jenkins

- name: Ensure podman containers config directory exists
  file:
    path: /home/jenkins/.config/containers
    state: directory
    recurse: yes
    owner: jenkins
    group: jenkins

- name: Copy podman registries mirror config file
  copy:
    src: data/config/podman/registries.conf
    dest: /home/jenkins/.config/containers/registries.conf
    owner: jenkins
    group: jenkins
    mode: '0644'

- name: Copy testcontainers config file
  copy:
    src: data/config/testcontainers/.testcontainers.properties
    dest: /home/jenkins/.testcontainers.properties
    owner: jenkins
    group: jenkins
    mode: '0644'

### Installing pip packages ###
- name: Install pip packages
  pip:
    name:
      - cekit
      - behave
      - lxml
      - docker
      - docker-squash
      - odcs[client]
      - elementPath
      - pyyaml
      - ruamel.yaml
      - python-dateutil
    executable: /bin/pip3
...